services:
  analytics:
    container_name: dip_analytics
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8091:8091
    networks:
      - education
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    container_name: dip_analytics_postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dip_analytics
    ports:
      - 5432:5432
    networks:
      - education
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  education:
    driver: bridge
    external: true

volumes:
  static:
  postgres_data:
