"""added fields to road and car table and made table for many-to-many

Revision ID: 288619513aa1
Revises: 6c35f0617e33
Create Date: 2025-05-08 13:16:24.217881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288619513aa1'
down_revision: Union[str, None] = '6c35f0617e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table',
    sa.Column('road_id', sa.Uuid(), nullable=True),
    sa.Column('car_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['road_id'], ['road.id'], )
    )
    op.add_column('car', sa.Column('average_speed', sa.Integer(), nullable=False))
    op.add_column('car', sa.Column('road_id', sa.Uuid(), nullable=False))
    op.drop_index('idx_pages_created_at', table_name='car')
    op.drop_index('idx_car_plate_number', table_name='car')
    op.create_index('idx_car_plate_number', 'car', ['plate_number'], unique=True)
    op.create_index('idx_car_created_at', 'car', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_unique_constraint(None, 'car', ['plate_number'])
    op.create_foreign_key(None, 'car', 'road', ['road_id'], ['id'])
    op.drop_column('car', 'avarage_speed')
    op.drop_column('car', 'longitude')
    op.drop_column('car', 'latitude')
    op.add_column('road', sa.Column('street', sa.String(length=255), nullable=False))
    op.drop_index('idx_road_condition_created_at', table_name='roadcondition')
    op.create_index('idx_road_condition_created_at', 'roadcondition', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_road_condition_created_at', table_name='roadcondition', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_road_condition_created_at', 'roadcondition', [sa.text('created_at DESC')], unique=False)
    op.drop_column('road', 'street')
    op.add_column('car', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('car', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('car', sa.Column('avarage_speed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_car_road_id', 'car', type_='foreignkey')
    op.drop_constraint('uq_car_plate_number', 'car', type_='unique')
    op.drop_index('idx_car_created_at', table_name='car', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_car_plate_number', table_name='car')
    op.create_index('idx_car_plate_number', 'car', ['plate_number'], unique=False)
    op.create_index('idx_pages_created_at', 'car', [sa.text('created_at DESC')], unique=False)
    op.drop_column('car', 'road_id')
    op.drop_column('car', 'average_speed')
    op.drop_table('association_table')
    # ### end Alembic commands ###
