"""add indexes car road roadcondition

Revision ID: 6c35f0617e33
Revises: ec13c5531d23
Create Date: 2025-04-20 13:29:43.078450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c35f0617e33'
down_revision: Union[str, None] = 'ec13c5531d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pages_created_at', table_name='car')
    op.create_index('idx_pages_created_at', 'car', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('ix_road_city', table_name='road')
    op.create_index('idx_road_city', 'road', ['city'], unique=False)
    op.create_index('idx_road_name', 'road', ['name'], unique=True)
    op.create_index('idx_road_condition_created_at', 'roadcondition', ['created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_road_condition_created_at', table_name='roadcondition', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('idx_road_name', table_name='road')
    op.drop_index('idx_road_city', table_name='road')
    op.create_index('ix_road_city', 'road', ['city'], unique=False)
    op.drop_index('idx_pages_created_at', table_name='car', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_pages_created_at', 'car', [sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
